###
#@name Create index
PUT http://localhost:9200/persons
Content-Type: application/json

{
  "mappings": {
    "properties": {
      "first_name": {
        "type": "text"
      },
      "last_name": {
        "type": "text"
      }
    }
  }
}

###
#@name Upsert (update or insert)
# If the command is run multiply times, the record will be updated and the field _version will be incremented
PUT http://localhost:9200/persons/_doc/{{id}}
Content-Type: application/json

{
  "first_name": "{{first_name}}",
  "last_name": "{{last_name}}"
}

###
#@name Create
# If it is already exists, the 409 Conflict error will be thrown
PUT http://localhost:9200/persons/_create/{{id}}
Content-Type: application/json

{
  "first_name": "{{first_name}}",
  "last_name": "{{last_name}}"
}

###
#@name Get
GET http://localhost:9200/persons/_doc/{{id}}
Content-Type: application/json

###
#@name Delete
DELETE http://localhost:9200/persons/_doc/{{id}}
Content-Type: application/json

###
#@name Get all
GET http://localhost:9200/persons/_search
Content-Type: application/json
